@HOST = http://localhost:4000/api
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMSIsImV4cCI6MTcxNjYxODU2Nn0.N0WdxR4yZkI6IsuSz3uJnKLFCudahQm0-675MolcVsw
# @TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMiIsImV4cCI6MTcxNjYyMDk1NH0.7wa_bJXnKWAQGoaQE-JtfjKuoOOx-8KCLrl4-s6I5v0

###

GET  {{HOST}}/auth/user
Authorization: {{TOKEN}}

###

GET {{HOST}}/user
        ?page=
        &limit=2
        &keyword=
        &orderBy=id
        &sortedBy=asc
Authorization: {{TOKEN}}

###

GET {{HOST}}/user/kNj5VLv1lg
Authorization: {{TOKEN}}

###